### ISSUE TITLE
GIF text small size and white bar at bottom [date.animation.gif]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1013]
### Description

White bar on bottom (possibly no date as well) of GIFs (tested in SIT Chrome) and tiny text. This happens after creating a large GIF ~245mb at 1km resolution. The first (large GIF) has tiny text and a white bar at the bottom. Afterwards, large GIFs will be the same (tiny text/white bar) and small GIFs have the white bar on the bottom with normal text.

Tiny text & white bar - screenshot of 248mb large GIF 1 km resolution
![giftext](https://user-images.githubusercontent.com/24417194/40511031-8452fa14-5f6c-11e8-915f-76bbe46bd06d.png)

White bar - 780kb small GIF 10km resolution
![nasa-worldview-2018-05-17t00_00_00z-to-2018-05-24t00_00_00z 5](https://user-images.githubusercontent.com/24417194/40511009-6dea03a8-5f6c-11e8-99bc-56280ec4e134.gif)

### Steps to Reproduce

1. Create a GIF with 1km resolution and a request size of 245mb+
2. GIF preview should show tiny text and white bar at bottom of GIF
3. Try a smaller 10km resolution GIF and it should have white bar at bottom

**Expected behavior:**   
Create GIF with normal brand text and date/no white bar.

**Actual behavior:**   
GIF with tiny brand text and possibly no date (white text could be hidden) with white bar.

### Environment

Version: 2.5.0
Browser: [Chrome Windows ]

**Comment by Benjaki2** [comment]
@edplato Yikes nice find with the scary white bar 😨. I think the small text may be the desired functionality. The height of the worldview logo should be 60px (right now that is the set max) if you look at the image zoomed into to full resolution or on a large screen. We could make the font-size larger so that the logo/date-text is always proportional. I think I discussed this with @rboller and his thoughts were against having the text/logo too large too avoid covering up imagery but I could be wrong.  What are your thoughts on this @rboller ? Should we up the logo/text a bit more on hi-res imagery?
