### ISSUE TITLE
Can't download large file size GIFs

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1016]
### Description

In SIT 2.5.0, I haven't been able to download a large GIF 240mb+ in IE11 or Firefox after a few attempts. It seems to get stuck for 200mb as well for IE11. In Edge, I was having problems downloading a large GIF, but after a few more tests I can download a 240mb+ GIF in about 4 minutes, but a few warnings that show up and progress (loading icon/progress bar) is frozen while processing.

Chrome is fast and usually processes a 240mb GIF in under a minute with pretty consistent UI feedback with the loading icon and progress bar always moving, but these other browsers run into a lot of freezing and stuck loading icons/progress bars.

For IE11, Edge, and Firefox, it freezes on 'Creating GIF' for 240mb+ GIFs (haven't tested too many other sizes). For IE11, the progress bar just hangs at ~15% for 10+ minutes with no download. For Edge, sometimes it freezes on 'Loading' (with the GIF preview still visible) and other times, it gets to the 'Creating GIF' and the progress bar just remains empty. However, in Edge, on two attempts I was able to download a 240mb GIF that froze during download and had warning notifications that took just under 4 minutes. For Firefox, the progress bar froze at ~15% one time and 100% another and did not download the GIF. On one attempt, Firefox crashed the browser when trying to close the 'Creating GIF' dialog box.

**Overview Large GIFs (240mb+ tested):**
IE11 - freeze and doesn't download ~10+ minutes
Edge - freeze and does download ~4 minutes
Firefox - typically freeze and doesn't download ~10 minutes

### Console Warnings/ Notifcations

In IE11 and Firefox, console errors are showing up as 'Unhandled promise rejection out of memory'.

In Firefox, sometimes an alert with 'Warning: Unresponsive Script' shows up that gives the option to 'continue', 'debug script', or 'stop script'. Continuing allows progress to continue, but the alert blocks the page.

For Edge, on clicking 'Create Gif', a console warning comes up that says 'SCRIPT7016: Use of XMLHttpRequest with the synchronous flag set to true is deprecated due to its impact on user-perceived site performance.'.  Then a notification 'nasa.gov is not responding' is shown with the option to 'Recover webpage'. This notification disappears after a couple of seconds then comes back repeatedly.

### Steps to Reproduce

1. Create GIF > 240mb (or see browser specifics above)

### Environment

Version: 2.5.0
Browser: [IE11 | Edge | Firefox]

References #816

**Comment by mike-mcgann** [comment]
What are the dimensions of a 240mb GIF?

**Comment by edplato** [comment]
They range in dimensions due to precise dragging of the target GIF to try and get the request size to 240mb, but are roughly 3283 x 3283px, for example, and use the 1km resolution.

**Comment by Benjaki2** [comment]
Hey @edplato @mike-mcgann @rboller . I have a few ideas for addressing this issue but I think that just lowering the max download could be the solution for this release since on production (v2.4.0) we are limited to less than 50mb even with chrome so this is a huge improvement. The browser freezes like this in IE on production when only requesting ~36mb (though this was tested with browserstack so it might not be that bad 🤞). 

Possible enhancements (though i'm sure there are others):
* Make the max download amount browser-specific
* Create a queue for requesting images so that browser isn't requesting all the images at once.
* Create a limit for the dimensions as opposed to lowering the total request size limit. I think that with the current implementation the individual frame size is the limiting factor more than the overall size

What are your all's thoughts on what should be implemented for release `2.5.0` and what should be saved for a follow-up release?

**Comment by edplato** [comment]
I would suggest lowering the max download for now and getting it out to 2.5.0 since your enhancement is huge when comparing 2.4.0 vs 2.5.0 SIT download times. Here are the results from a benchmark test I put together recently for ~39.6MB GIF download time:

| Browser        | 2.4.0 (time)          | 2.5.0 SIT (time)  |
| ------------- |:-------------:| -----:|
| IE11      | 5:09 | 0:39 |
| EDGE     | 4:25      |   0:32 |
| FIREFOX | 0:26    |    0:20 |
| CHROME      | 0:18      |   0:12 |

I didn't test Safari, but I'm sure it's impressive as well.

**Comment by Benjaki2** [comment]
Wow, Crazy! Thanks for putting that together!

**Comment by minniewong** [comment]
Fixed
