### ISSUE TITLE
Redo Timeline in React

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#108]

**Comment by polluxll** [comment]
I want to add my own data on worldview,but the time step is hourly.dose the timeline support the hourly data?

**Comment by Benjaki2** [comment]
As the code sits now, you can't show sub-daily timescales on the timeline. I don't think that it would take too much tweaking of the timeline module to accommodate for another zoom level. However, the current implementation of the timeline is not the most scalable and that is the purpose of this issue. Upon completion of this issue, the idea is that you will be able to insert any scale to the props of the component and the timeline will respond dynamically. Let me know if you would be interested in collaborating with us on this effort or if you would like to be pointed in the right direction so that you can do your own 'quick-fix'.

**Comment by polluxll** [comment]
thanks, I will have a try。

**Comment by ZachTRice** [comment]
Currently the timeline has an issue in FF with the svg width being calculated. When you drag the window, the timeline breaks to the next line briefly. This is not a huge issue but something to note when we convert to react.

**Comment by minniewong** [comment]
Won't redo timeline in React but will work on timeline in #555
