### ISSUE TITLE
Allow slower animation speeds

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#114]

**Comment by Benjaki2** [comment]
@rboller I plan to change slider increments from 1 fps to 0.5 fps and have the range be 0.5 -10 fps. What are your thoughts?

**Comment by rboller** [comment]
Yesterday I asked the user who suggested the slowdown for a sense of how slow they'd like to see it.  Haven't heard back yet but your approach seems like a good way to keep the scale linear.

Otherwise if there's a way to manually add what each increment of the slider is, you could make it non-linear until it gets to 1 fps.  E.g., 
0.1 0.2 0.4 0.8 1.0 2.0 3.0 ... 10.0

**Comment by Benjaki2** [comment]
I agree, a nonlinear approach would be better. The slider module we are currently using doesn't support non-linear increments so it would require a little bit of dev time to choose another slider component or to create a custom slider.

**Comment by rboller** [comment]
Ok, let's give your 0.5 - 10 fps via 0.5 fps increments a try and see how it goes.  If it's not too granular and we need it to be slower, we could go down to a 0.25 minimum with 0.25 increments.

**Comment by rboller** [comment]
User wrote back to say 0.5 fps should be fine.
