### ISSUE TITLE
Notification window covers entire viewport

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1181]
**Describe the bug**
When I click the notifications button in the "i" info menu, the modal opens up to be 100% of the viewport. 

**Screenshots**
![screenshot_6](https://user-images.githubusercontent.com/17348884/43934496-95becd26-9c1d-11e8-95cd-54cd1d3dfeb7.png)

**Desktop (please complete the following information):**
 - Window Chrome & Window FireFox  (IE11 & Edge are fine)
 - Version 2.7.1

**Comment by ZachTRice** [comment]
I was not able to reproduce on a separate machine running same browsers/versions. Needs additional verification.

**Comment by Benjaki2** [comment]
Not seeing this seeing this in chrome or firefox on my OSX machine.

**Comment by edplato** [comment]
I've encountered this once before on Windows Chrome, but haven't been able to reproduce it since. I was doing a lot of testing related to window resizing at the time. This might be a good place to look [worldview/web/js/notifications/ui.js line 429-441](https://github.com/nasa-gibs/worldview/blob/440fd32ced12ad3f69f3be40c3970b852570b720/web/js/notifications/ui.js#L429-L441)

**Comment by minniewong** [comment]
can't reproduce
