### ISSUE TITLE
Change displayed units

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1196]
Be able to switch the units displayed (Celsius instead of Kelvin)

**Comment by rboller** [comment]
UI options:
1. make the units for a given layer clickable (similar to lat/lon toggle) which then cycle through alternate units; user preference saved in local storage but not necessarily in permalink
2. if units are changed for a given layer (e.g., Kelvin to Celsius), all other layers with the same unit will also be changed when/if loaded (i.e., they're all now in Celsius instead of Kelvin)
3. an alternative for item 2 would be that it would be more of a global toggle between metric/imperial/etc units for all layers

**Comment by mcechini** [comment]
Does this force us into more of a "controlled value" list of units in the colormaps?  (Note someday this would also be in UMM-Vis... which may be a more appropriate place for a controlled list).

**Comment by rboller** [comment]
@mcechini I think that's TBD but seems like that would be a prudent thing to do if this will be a comprehensive feature covering a lot of units.

That said, we're currently considering this functionality for only a small set of units to start so probably don't need to go too far in formalizing it yet.

**Comment by rboller** [comment]
We decided that this feature could cause more trouble than it's worth.  Closing for now unless the pros outweigh the cons in the future.

**Comment by minniewong** [comment]
Will consider a simple approach for temperature layers
