### ISSUE TITLE
Check GIBS Google Maps example

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#122]
https://github.com/nasa-gibs/gibs-web-examples#google-maps
https://earthdata.nasa.gov/labs/gibs/examples/google/webmercator-epsg3857.html

**Comment by rboller** [comment]
The problem is on the GIBS side - during MODIS C6 atmosphere reprocessing, the older web mercator imagery was deleted and is currently being done on a forward processing basis.  

Eventually this will be addressed by GIBS' on-the-fly reprojection.  Until then, they agreed to reprocess the single date used in the GIBS Web Examples.  More details in GIBS-1969.

**Comment by rboller** [comment]
GIBS backfilled that date and the examples work again
