### ISSUE TITLE
When you take the tour, the date changes back to today

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1245]
1. Change the date to something other than today
2. Click on the 'i' button
3. Click on 'Start Tour'
4. The first step of the tour changes the date to today and changes the app back to the initial state (removing any layers you've added)

I think the date should remain whatever you had changed it to. Perhaps that functionality was fine before but it might be confusing now when you go into comparison mode from the tour, the date will change in whichever active tab you were in and when you re-enter comparison mode, you date has now changed and you've lost the layers you added earlier.

**Comment by mike-mcgann** [comment]
We decided that going to a known state when starting the tour was desirable. This issue came up because when a user has a polar projection selected, the instructions in the tour don't match up what is seen in the interface. If you change the projection while in the tour, it will reset it back to geographic when you move to the next step. 

This is probably more along those lines. When entering comparison mode from the tour, the instructions no longer match up with what is seen in the interface. Resetting when moving to the next step might work or just disable comparison mode outright. 

But, that being said, I don't think it is worth investing any time into improving the current tour process since that is scheduled for replacement. I think it is okay, as-is, for now.
