### ISSUE TITLE
Update share options for social media

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#140]
Add ability to share directly to twitter or facebook when you click the share icon. Additionally, there would be a "copy link" option to support the existing option.  Maybe also have a "email" option.

**Comment by rboller** [comment]
Agreed, back in Jira-land (WV-1582) we also discussed this but haven't pulled the ticket over to here yet.

**Comment by rboller** [comment]
The new [State of the Oceans](https://podaac-tools.jpl.nasa.gov/soto/) has a nice share feature which includes direct links to social media.  We might look at doing something similar.

**Comment by rboller** [comment]
It would also be nice if this showed a preview image (which will probably be static) as discussed in WV-1665.

**Comment by minniewong** [comment]
The share should include a generic image of Worldview or if easy enough, a snapshot of the actual URL being shared.

**Comment by minniewong** [comment]
Focus on Twitter and Facebook; look into Instagram

**Comment by ZachTRice** [comment]
You cannot share media on Instagram using the API. Here is their reasoning:

> At this time, uploading via the API is not possible. We made a conscious choice not to add this for the following reasons:
> 
> Instagram is about your life on the go – we hope to encourage photos from within the app.
> We want to fight spam & low quality photos. Once we allow uploading from other sources, it's harder to control what comes into the Instagram ecosystem. All this being said, we're working on ways to ensure users have a consistent and high-quality experience on our platform.
>

**Comment by ZachTRice** [comment]
For Twitter: If you look at the [State of the Oceans](https://podaac-tools.jpl.nasa.gov/soto/) sharing feature, when you share a Tweet on there, the user experience is not very good because nothing is being passed to the text box, including the URL. The intended action will be to write a short message and have a shortned link afterwards.

I am thinking something along the lines of:
> Check out what I found in NASA's Worldview - Shortened_URL

Without any information passed, there is no reference back to what was suppose to be shared and in the case of SOTO, it is up to the user to navigate back to the page and add text + a link.

@rboller, @minniewong Let me know what you think of the sharing text I came up with. Ideally the text should be as short as possible. The shortened link will use up to 30 of the 140 character maximum. If the message is 40 characters then that still leaves about 70 characters for the end-user to add his own text to the message.

**Comment by minniewong** [comment]
Or some text that incorporates #NASAWorldview
(Other users, and our communications people, use that hastag - https://twitter.com/hashtag/NASAWorldview?src=hash)

**Comment by rboller** [comment]
Agreed with both of you.  That would make something like:

> Check out what I found in #NASAWorldview - (shortened link)

**Comment by minniewong** [comment]
Connects to #328

**Comment by minniewong** [comment]
Connects to #328

**Comment by minniewong** [comment]
Connects to #328

**Comment by minniewong** [comment]
Connects to #328
