### ISSUE TITLE
Multiple layers show "error loading metadata" in search results

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1444]
**Describe the bug**

When using the search feature in the layer modal, the "i" button description shows "There was an error loading layer metadata" for multiple layers.

**To Reproduce**
1. Open Add Layers
2. Search "Aerosol Optical Thickness 550nm (Daily)"
3. Click the "i" button for Aerosol Optical Thickness 550nm (Daily)

**Expected behavior**
Either no text should appear or a description should appear here.

**Screenshots**
![screenshot_34](https://user-images.githubusercontent.com/17348884/47793182-122efb80-dcf4-11e8-8b61-38bdaea811be.png)

**Desktop (please complete the following information):**
- Production and SIT; Windows Chrome

**Additional context**
 I see this happening with the following layers (though probably happening with more):
- Aerosol Optical Thickness 550nm (Daily)
- Aerosol Angstrom Exponent (Daily)
- Aerosol Optical Thickness 550nm (Monthly)
- Aerosol Angstrom Exponent (Monthly)
- Total Aerosol Optical Thickness Scattering 550nm (Monthly)
- Total Aerosol Optical Thickness Extinction 550nm (Monthly)
- Aerosol Optical Depth Analysis (Monthly)

**Comment by minniewong** [comment]
If there is a 404 provide message that says "no metadata available"

**Comment by jasontk19** [comment]
@ZachTRice  @minniewong 
This appears to have been fixed for some time. The code in place only shows an error message if the request fails or if the metadata file fails a regex check for script/style tags: https://github.com/nasa-gibs/worldview/commit/d7af9024d9759f8f81b85703d810ab4baa9cd6b7#diff-9f321bd238516e266690605a18d90765R50-R58

The result is simply blank (with the exception of time ranges) if no metadata is found.  Do we want to add a message saying "no metadata found"?  Seems like that might look weird next to info about available time ranges since that basically _is_ metadata.

![Screen Shot 2019-10-04 at 12 30 00 PM](https://user-images.githubusercontent.com/1480000/66223949-b9ee3f80-e6a2-11e9-87ed-0ee68655979c.png)
