### ISSUE TITLE
Imagery missing

### ISSUE THREAD

**Issue by mikeacres** [nasa-gibs/worldview#1621]
What are the black sections where no data is displayed? (see image below) 

I imagined they were due to the natural curvature of the earth being displayed as a flat image, however when I wrap that flat rectangular image around a spherical object the black sections are still present.

Any suggestions/advice would be greatly appreciated.  

Michael

**Comment by mikeacres** [comment]
My image link isn't uploading nor can I paste an image into my comment. I am referring to the black areas visible when zoomed completely out of any image in Worldview. Hope that explains.

**Comment by minniewong** [comment]
Hi Mike, 
When you are viewing the Terra/MODIS and Aqua/MODIS Corrected Reflectance imagery the black gaps are the swath gaps at the equator. The swath width of the sensor is 2,330 km wide. When you view the Suomi-NPP/VIIRS (a newer sensor/satellite launched in 2011) Corrected Reflectance Imagery there are no black swath gaps because the swath width is 3,040 km wide which enables ~15% image overlap between consecutive orbits at the equator. See the video "Aqua MODIS instrument sensing" to see how the gaps occur: https://aqua.nasa.gov/visualizations?page=1, Since the Suomi-NPP/VIIRS instrument has wider swaths, you don't see the gaps (https://www.nasa.gov/topics/earth/features/viirs-globe-east.html)

**Comment by mikeacres** [comment]
minnieong,
Thank you yet again for your assistance. I feel like I probably should have discovered that myself in all honesty so apologies for asking. 
I know the NASA data/imagery in worldview seems to be free to use assuming it is cited correctly but I am wondering if then importing it into google earth pro and wrapping it as a KMZ file changes the usage rights. Google Earth's guidelines are less clear.
Thank you again

**Comment by mikeacres** [comment]
@minniewong the imagery that is used in the worldview application is missing areas at the north or south depending on the month selected which when wrapped leaves an image gap 'hole' on either North or South pole. Is this due to natural movement of the earth over the year making either pole more of less visible during certain months?

**Comment by minniewong** [comment]
@mikeacres - This is due to the lack of reflected light during the winter in the north pole and the winter in the south pole. The reflectance imagery utilizes sunlight reflected off the surface of the earth.
