### ISSUE TITLE
Allow invalid text entry into date fields

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#1662]
The UI currently prevents you from typing certain dates into the date panel when they're deemed "invalid".

As it turns out, you sometimes need to type in an invalid date en route to a valid one.  E.g., 
- if the currently selected date is 2019 March 11 which is also the date in real life
- you want to change the selected date to 2018 June 15
- the interface requires you to first change the year to 2018 since "June" or "15" isn't available yet in 2019.

We should probably loosen this to allow invalid dates to be entered; we can still highlight which entries are invalid and not send any requests to GIBS while there are invalid entries.  It would just allow more flexibility while entering dates as a human might want to do.

**Comment by minniewong** [comment]
+1 
Especially a problem when trying to enter dates in the animation widget

**Comment by edplato** [comment]
A thought on how flexible to make the invalid date input from a previous discussion: If a user's goal is to change from 2/26 to 3/30, could the user select '30' while still in February then change from 'FEB' to 'MAR', or will the max day value be determined on the currently selected month and be limited to '28'?

**Comment by ZachTRice** [comment]
What if the max date is always "31" on the day input. If you are in a month, like Feb, and type 30, it will turn the box red and the map won't select anything new until you fix it. But, you aren't locked to the box. You would be able to move to month/year and change those values before coming back to correct the date. When you enter a correct date, the red goes away and the date is selected. 

This would probably work the same for if you are moving left/right through the months using the interval arrows. the box would turn red and you won't get new data if it is invalid; this way you could scroll through the months on 30 even as you pass Feb (rather than kicking you down to 28 as you pass Feb)

**Comment by ZachTRice** [comment]
So, my thought would be make the max date always 31 and not dependent on the month.
