### ISSUE TITLE
Run Browserstack E2E tests on Dependabot branches 

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1966]
**Is your feature request related to a problem? Please describe.**
Checking dependabot pull requests can become overwhelming if you have to pull down each branch and manually run e2e tests. To ensure dependabot is not breaking anything visually on the site, we should have those branches run e2e tests via browserstack. This will allow us to view the reports after the branch has been created.

**Describe the solution you'd like**
Write a regular expression to target dependabot branches:   
- https://docs.travis-ci.com/user/customizing-the-build/#using-regular-expressions
- Fallback aproach: https://docs.travis-ci.com/user/customizing-the-build/#using-regular-expressions

**Describe alternatives you've considered**
- Don't run e2e tests via browserstack.
- Run separate dependabot specific tests

**Additional context**
Works towards implementing E2E tests in Travis was previously explored in this ticket: https://github.com/nasa-gibs/worldview/issues/939

**Comment by ZachTRice** [comment]
Browserstack is currently silently failing. Our browserstack config file is overly complex and should be refactored to make updates easier (i.e. remove all the array variable looping behavior). This work needs to be done first before Dependabot can start using browserstack.

**Comment by jasontk19** [comment]
After a few days of working at this, my conclusion is that our browserstack e2e tests in their current form cannot be reliably run on Travis due to the fact that the build timeout for free accounts is 50 minutes and the browserstack tests take at least 45-50 minutes while running on Travis.  Reducing the number of OS/Browser combos configured did not seem to noticeably improve the run time since they run in parallel on Browserstack anyway.  I think the biggest factor here may be that we are running and hosting the app on Travis which likely provides limited resources which means the app is going to run slow and that individual test cases are much more likely to time out.  If we could deploy it to our own servers and trigger Browserstack from Travis to run against that, I'm guessing it would improve the run time since when we host the app locally and run Browserstack it only takes about 30 minutes.

In addition to the timeout issue, there was a problem with getting the Nightwatch e2e logs from Browerstack to completely display in Travis.  Only about 2/3 of the logs from a single OS/browser run are displayed before Travis truncates them and moves to the next build phase.  This means that you can't see the total pass/fail summary which makes running them useless.  I thought this issue might indicate the fix but was not able to get the solutions outlined here to work: https://github.com/travis-ci/travis-ci/issues/6018

I think the problem might be that we were calling `process.exit()` in our `browserstack.js` and so have updated it to instead just set the exit code and allow the process to exit when it completes, as the Node docs indicate here: https://nodejs.org/api/process.html#process_process_exit_code
I am hoping this would fix the log truncation issue but the Travis build timed out every time I tried to run it once implementing this change so it's still unknown.

For now, I think the best solution is probably to just run e2e headless locally in Travis.  We can do one build that does Firefox and one that does Chrome so they can run in parallel.  Running the e2e test headless only takes about 5-10 minutes and so should not noticeably degrade Travis build completion times.  Even though the initial goal was to run Browerstack E2E tests on dependabot branches only, since the build time increase is minimal for running e2e headless, I think it would be beneficial to run these on every build, which will be the plan for now.

**Comment by ZachTRice** [comment]
Good investigative work here. Sounds like a plan to run on Travis.
