### ISSUE TITLE
Starting fire tour while in polar projection causes crash

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#2023]
**Describe the bug**
When in Arctic or Antarctic mode and then click the "Satellite Detections of Fire" tour story, the page triggers a `Uncaught Error: Reference_Features: Invalid source: undefined` error and the map becomes unusable.

**To Reproduce**
1. Go to a polar projection or take the "Pine Island Glacier" tour story
2. Bring up the tour story menu either by clicking "Explore Worldview" or finishing the PIG story above
3. Select the "Satellite Detections of Fire" tour story

Observed in Mac FF/Chrome.

**Comment by edplato** [comment]
From what I can find, the main problem is that upon clicking the Satellite Detections of Fire story, antarctic layers are being requested in the geographic projection. Here is some debugging related to the projection state that may be the cause or effect of this issue. While logging out the `proj` state in `web\js\map\ui.js#L187` 

Click Pine Island Glacier tour from geographic projection
* `proj.id` and `proj.selected` match projections
![image](https://user-images.githubusercontent.com/24417194/63430791-7473fc80-c3eb-11e9-8318-08db1f6ebb45.png)

Click Satellite Detections of Fire from antarctic projection
* `proj.id` and `proj.selected` do **not** match projections
![image](https://user-images.githubusercontent.com/24417194/63430799-7a69dd80-c3eb-11e9-9351-9c97aecd2dd3.png)

**Comment by jasontk19** [comment]
@edplato It looks like the `stepLink` defined in this particular tour don't include the projection param in the URL (`p=geographic`) while every other tour does.  I can only assume this means we are always expecting to include this.  It may be worth adding some code that assumes `geographic` is the default projection for a tour step if none is included.  

I assume the way that most tours are created is that someone like @minniewong uses the app and configures it how they want then, copies the location state from the URL bar.  Since we don't include the projection as a param unless you've changed it, I imagine it's easy to forget to add this when creating new tours since they will work fine unless you've switched to `arctic` or `antarctic` before running them.

I will open a PR to add the projection param to this tour as a quickfix, then spend some time investigating a reliable way to assume `geographic` as the default if no projection is included in the `stepLink` for a particular step within a tour.

**Comment by ZachTRice** [comment]
These links worked without this parameter `pre-v3.0`. We should probably handle it the same way but it's @minniewong call since she is the one curating these.

I'm on board with just adding a quick fix for now and addressing the broader issue in a separate fix.

**Comment by minniewong** [comment]
I think I'd like it handled the same was a pre-v3.0 because it will be very easy to forget to add the projection parameter in for geographic, but agree that the quick fix works well and that we should investigate something else for the long term.

**Comment by jasontk19** [comment]
So, I'm not against adding a fix to default to `geographic` but I am curious why this projection is included in every `stepLink` for every other tour config if this worked without it before?  Did we change something about when this param appears (not showing in the URL if it's the default and is currently selected for example)?

**Comment by jasontk19** [comment]
I was curious to see how we used to handle this and tried the following:
* checked out v2.17 
* removed `p=geographic` from the first few `stepLink`s in the sunglint tour
* built/started the app
* switched to arctic projection
* started the sunglint story

The result was that the app did not switch to geographic projection when the tour started.  Do we think it worked in an even older version?
