### ISSUE TITLE
Can't open animation widget if custom interval is selected without set time unit

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2220]
**Describe the bug**
If the user selects `CUSTOM` timescale interval without setting the time unit, the animation widget is unable to open.

**To Reproduce**
1. Change timescale interval from `1 DAY` to `CUSTOM`
2. This opens the custom interval panel - close it without changing the time unit or delta
3. Click on `Setup Animation` button
4. Note animation widget is not opening
5. See console error

**Expected behavior**
Animation widget can open if no custom interval is set. Default to set interval/delta.

**Screenshots**
Console error (IE11 shown): 
![image](https://user-images.githubusercontent.com/24417194/66316835-5bb19e80-e8e6-11e9-8ff7-a97739e7fcdf.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE11 / Chrome

**Comment by jasontk19** [comment]
I'd like to change the way this interaction works a little bit.  @edplato @rboller let me know what you think.

1. Clicking on "CUSTOM" should open the dialog, but not change the interval to "custom" or alter it in any way yet (this alone should fix the bug since no unusable interval is set)
2. Add a small "OK" or "Set" button to the dialog so that you have to make a confirmation of your interval selection. Clicking this after interval selection closes the dialog. This feels preferable to closing/confirming the dialog with an "x" since that kind of interaction is usually reserved for a "Cancel" operation where you _don't_ want to keep your changes.
3. Clicking "x" in the dialog does not update the custom interval on the timeline/animation from what it was previously (if it was changed in the modal) but simply closes the dialog.

**Comment by edplato** [comment]
Using an "OK" or "Set" button was actually used in my first iteration, but the team feedback determined it was an extra step so it was removed. If we want to stick to the current design, maybe we can make it so the previous interval is retained in the child state that way if the user opens the panel and closes it without selecting a time unit then it reverts to the previous interval.

**Comment by jasontk19** [comment]
Hmmm, it wouldn't be an extra step if the "OK" button closed the dialog though right?

**Comment by jasontk19** [comment]
There is also currently a bug in production similar to this one where, if you select "CUSTOM" but don't set an interval, the timeline can't be stepped forward or backwards.  The above mentioned approach should solve both of these issues.
