### ISSUE TITLE
Animation playback hanging / looping issue

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#2399]
1. If you click the play button, it starts to play without pre-caching… and then gets hung when it does try to cache during mid-playback:
https://go.nasa.gov/2WTrU3K

2. If you hide the fire layer from the link above and start a playback, it also starts to play without pre-caching... but rather than hanging, it doesn't loop as it should:
https://go.nasa.gov/2CpdDCm

My speculation is that case 2 doesn't hang in the middle of playback since fires are disabled which can take noticeably longer to load than the standard imagery tiles...  so tile loading is keeping up with the playback speed in that case.  But something is still off which causes the looping to fail.

**Comment by jasontk19** [comment]
This doesn't appear to be a problem with slow loading imagery.  Rather, this appears to be an issue of date times and how the image pre-caching works.  In this link, the app time is `2019-10-29T22:00Z` but the animation start time is `2019-10-29T00:00Z`.  If I set the app time to `T00:00Z` to be in sync with the animation time, the issue does not occur. 

Here is the same link with the time rounded down to be in sync with the animation start time: https://go.nasa.gov/34LGZHe

Will need more investigation to determine the right fix.

**Comment by jasontk19** [comment]
The primary issue here is that, if you start an animation on a date/time within the start/end date range that is not snapped to the playback interval, the date/times for frames on subsequent playbacks don't match which confuses the queueing/preloading and looping logic, causing the animation to hang and/or preloading to stutter and hang.

We could probably hack it to allow starting playback from any point within the animation range, and then snap to the proper intervals on subsequent play throughs but, that would cause the first play through to possibly show different times (and imagery) which could be confusing or misleading.  On some occasions this seems to be happening currently (which is why we aren't seeing this bug more often).

But, the proper solution here would be to always snap the current date/time to a proper frame within the start/end date range of the animation based on the interval and continue playback from there.
