### ISSUE TITLE
Shorter orbit track layers in sidebar layer list

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2400]
**What existing feature could be improved?**
Currently, the orbit tracks are pretty tall compared to other layers.

**Describe the improvement you'd like**

**Current:**
![image](https://user-images.githubusercontent.com/24417194/68502706-15c26000-022f-11ea-9704-1e36ebf80d08.png)
**Revised:**
![shorter-orbit-layer](https://user-images.githubusercontent.com/24417194/68502699-10fdac00-022f-11ea-9768-5494ec976c51.png)

**Additional context**
This may be able to be extended to other single legend layers.

**Comment by jasontk19** [comment]
Here's what I was thinking:
![track-layer](https://user-images.githubusercontent.com/1480000/68504613-5b812780-0233-11ea-8abc-791f725759bb.png)

So that extra space on the bottom (in the original) is where we show the details on hover of the "classification" box.  My thinking was to just show this as a tooltip on hover so we don't have to dedicate that whitespace for this purpose.  This approach should translate well to any other layers with classification palettes I believe.

**Comment by edplato** [comment]
I like it. Looks clean and saves space. On a side note, I see the eye version 1.0 is back 👁😄

**Comment by jasontk19** [comment]
Or, we could include the classification label next to the box in cases where there is only one classification, like so:

![track-layer2](https://user-images.githubusercontent.com/1480000/68504951-2cb78100-0234-11ea-90a3-554129a52c9b.png)

The icons look a little different because I imported an old version of font-awesome icons into Sketch.

**Comment by minniewong** [comment]
I think it's good to have all the important information together `Aqua - Ascending/Day`; but the classification label is probably good to keep also

**Comment by jasontk19** [comment]
Note to self: may be able to fix #1684 as part of these changes.
