### ISSUE TITLE
Sea Surface Height imagery not loading under certain circumstances

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#2540]
1. Go here: https://worldview.earthdata.nasa.gov/?v=-206.10371515515007,-105.98355893735533,186.889492607407,110.12570032190393&t=2014-05-04-T17%3A10%3A21Z&l=TOPEX-Poseidon_JASON_Sea_Surface_Height_Anomalies_GDR_Cycles,Coastlines
2. Go back 1 day --> No image. (presumably no data at this date, but that may be a separate issue)
3. Go forward 1 day --> No image. (should have been the image from step 1)
4. Go forward 1 month then go back 1 month --> See image. (image from step 1)

Step 3 is unexpected.

--

This might be related. The flyout says “Temporal coverage: 2 October 1992 - 22 November 2017” but I’m not seeing images for all of those dates. There seems to be a block between 2014-MAY-04 and 2015-APR-25 but earlier and later images seem to be mostly unavailable and when they are available they seem to appear and disappear inconsistently when navigating the calendar widget.

Also, these should be available to July 2019

--

Also note that the date ranges for that product are quite variable as described in the GetCapabilities which may be a factor:

```
<Value>1992-10-03/1992-10-03/P8D</Value>
<Value>1992-10-13/1995-11-17/P10D</Value>
<Value>1995-11-26/1995-11-26/P9D</Value>
<Value>1995-12-07/1995-12-07/P1D</Value>
<Value>1995-12-17/1999-02-09/P10D</Value>
<Value>1999-02-19/1999-02-19/P8D</Value>
<Value>1999-03-01/2003-11-10/P10D</Value>
<Value>2003-11-19/2003-11-19/P9D</Value>
<Value>2003-11-30/2003-11-30/P2D</Value>
<Value>2003-12-10/2004-02-07/P10D</Value>
<Value>2004-02-15/2004-02-15/P8D</Value>
<Value>2004-02-27/2004-02-27/P7D</Value>
<Value>2004-03-08/2005-09-14/P10D</Value>
<Value>2005-09-20/2005-10-04/P7D</Value>
<Value>2005-10-14/2006-10-26/P10D</Value>
<Value>2006-10-30/2006-10-30/P5D</Value>
<Value>2006-11-25/2006-11-25/P9D</Value>
<Value>2006-12-05/2013-03-23/P10D</Value>
<Value>2013-03-30/2013-03-30/P8D</Value>
<Value>2013-04-12/2013-04-12/P7D</Value>
<Value>2013-04-22/2013-08-29/P10D</Value>
<Value>2013-09-05/2013-09-05/P8D</Value>
<Value>2013-09-17/2013-09-17/P6D</Value>
<Value>2013-09-27/2014-04-24/P10D</Value>
<Value>2014-05-04/2014-05-04/P9D</Value>
<Value>2014-05-13/2014-12-08/P10D</Value>
<Value>2014-12-17/2014-12-17/P9D</Value>
<Value>2014-12-27/2017-11-13/P10D</Value>
```

**Comment by edplato** [comment]
![image](https://user-images.githubusercontent.com/24417194/72110636-b0f6b500-3306-11ea-9622-a870529d46e9.png)
**5/4/2014 to 5/14/2014 to 5/3/2014**

It appears that earlier dates are being added to the available coverage dates out of order. This causes the missing layer from step 3 due to the app using a previous date that isn't actually a previous date since it's out of order.

Preventing earlier dates from being added after later dates seems to fix this:
![image](https://user-images.githubusercontent.com/24417194/72110865-3e3a0980-3307-11ea-90e9-e869020fb389.png)
**5/4/2014 to 5/14/2014 to 5/21/2014**
