### ISSUE TITLE
Add data download handler for VIIRS fires

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#260]
Probably has a shortname of VNP14IMG_NRT

**Comment by minniewong** [comment]
Using the "MODISSwath" data download handler for the VIIRS fires shows the correct granules but does not show the swath line that connects the granules (see 1st image) like the actual MODIS Fires data download does (see 2nd image). @rboller Do we need a new data download handler for VIIRS? 
![screen shot 2017-05-23 at 10 41 46 am](https://cloud.githubusercontent.com/assets/10747923/26359880/98b0a01c-3fa4-11e7-91d6-8e2234b0dc8f.png) - VIIRS Fire Data Download
![screen shot 2017-05-23 at 10 43 01 am](https://cloud.githubusercontent.com/assets/10747923/26359886/9b87cf22-3fa4-11e7-953d-0e4e6e2585f2.png) - MODIS Terra Fire Data Download

**Comment by rboller** [comment]
@minniewong I'll take a look at the differences between the VIIRS and MODIS metadata from CMR and see what needs to be done.  We might be able to update the existing MODIS handler to work with VIIRS, otherwise I'll create a new handler.

**Comment by localjo** [comment]
@minniewong I'm having trouble finding these data sets. Can you help?

I added all of the layers I could find related to VIIRS and thermal anomalies;
![screen shot 2018-01-25 at 5 03 09 pm](https://user-images.githubusercontent.com/516388/35414855-bff04028-01f1-11e8-88e6-476bee84b8f0.png)

But this is the only data that shows up to download;
![screen shot 2018-01-25 at 5 02 59 pm](https://user-images.githubusercontent.com/516388/35414878-d0336ce4-01f1-11e8-9b8a-118e08326543.png)

All of the granules and swath lines [appear to be working for those products](https://go.nasa.gov/2GkeKUL).

**Comment by localjo** [comment]
It looks like the `MODISSwath` data handler is iterating over a variable called `startTimes` that looks like this;
```
  var sst = {
    '2018-01-30T23:55:00.000Z': [{
      browse_flag: true,
      centroid: { 'EPSG:4326': {} },
      coordinate_system: 'GEODETIC',
      data_center: 'LPDAAC_ECS',
      dataset_id: 'MODIS/Aqua Thermal Anomalies/Fire 5-Min L2 Swath 1km V006',
      day_night_flag: 'DAY',
      downloadLabel: '2018-01-30: 23:55-00:00 UTC',
      feature: { revision_: 1, ol_uid: 2061, geometryName_: 'geometry' },
      geometry: { 'EPSG:4326': {} },
      granule_size: '0.326846',
      id: 'G1452340135-LPDAAC_ECS',
      label: '23:55 - 00:00 UTC (-1 day)',
      links: [ {}, {}, {} ],
      online_access_flag: true,
      orbit_calculated_spatial_domains: [ {} ],
      original_format: 'ECHO10',
      polygons: [ [] ],
      producer_granule_id: 'MYD14.A2018030.2355.006.2018031114512.hdf',
      product: 'MYD14',
      time_end: '2018-01-31T00:00:00.000Z',
      time_start: '2018-01-30T23:55:00.000Z',
      title: 'SC:MYD14.006:2284569353',
      updated: '2018-01-31T12:06:31.026Z',
      urs: false,
      version: 6
    }, {...}, {...}],
    '2018-01-31T00:30:00.000Z': [{...}, {...}],
    '2018-01-31T01:20:00.000Z': [{...}, {...}],
    ...
  };
```

And the reason the same handler doesn't work for VIIRS fires is because the timestamp keys only contain one object in their array. I'm not sure what those objects are, but they're assigned to a variable called `swath` in Worldview. @rboller @mcechini Can either of you shed light on what those objects represent, and why VIIRS would only have one of them in each array, where MODIS has multiple?

**Comment by ZachTRice** [comment]
The issue seems to revolve around how the swath object groups granules. The swath object should be grouping granules in an array based on the distance between their centroid coordinates being less than a defined max distance. Granules within an array group then have a vector line drawn between them. 

That vector line should be drawn within `updateSwaths` in `web/js/data/map.js`, since `OlGeomLineString` is the openlayers method for creating a line between two points based on coordinates. Though there are additional methods for detecting distance & connecting swaths / granules within `web/js/data/results.js`,such as `combineSwath` and `connectionAllowed` which could also be related.

**Comment by mike-mcgann** [comment]
Swaths were being connected by matching up the end time of one granule with the start time of another. For MODIS, a granule with times 1:30-1:35 would connect to a granule with times of 1:35-1:40. 

VIIRS has a one minute gap in the metadata for connecting granules. The times would instead be like 1:30-1:34 and 1:35-1:39. The code didn't expect that it and now can take a `delta` parameter which specifies, in seconds, the gap between granules.
