### ISSUE TITLE
Optimize product picker search and load

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#269]
As we continue to add many new products, the performance of the product picker is beginning to degrade.  Currently the main problem is a slowdown in the search feature.  

A secondary problem is visible in the GIBS preview instance in that the load time of the app is much slower.  It's not clear if it's related to pre-loading all of the products but seems like a good candidate given that there are many additional test layers available in that instance.

**Comment by tgunnoe** [comment]
The size of our json config file is just under 500KB. This doesn't scale well in the long run, so it should be kept in mind that this will probably need to be migrated to another format in the future.

I can definitely optimize the search function so that it doesnt hang when typing in strings to filter by.  The current search function dates back to the old add tab search UI.

The load is its own problem though, and it is what heavily degrades the GIBS client at initialization.  Their json config file is ~850KB (uat-ext at least).  That may still only take a few seconds to load into WV, but trying to print all the values of it in the product picker is where the noticeable degradation resides.  I think this can be fixed by either pagination or infinite scroll.  I'd go with the latter for implementation as it wouldnt require much change of UX and the libraries we're using for scrolling (perfect-scrollbar) and sorting in the product picker (isotope) both have examples of using it.

Also, I probably would no longer load the product picker items until after the add layers button is pressed.  Before we wanted most of Worldview loaded upon initialization, but we could minimize that a lot by not loading the product picker until requested.  That would also allow GIBS/WV to not degrade up until that point, for starters.

**Comment by rboller** [comment]
@tgunnoe that all sounds like a good path forward to me.
