### ISSUE TITLE
Make mobile menu items easier to select 

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2713]
**What existing feature could be improved?**
Currently, it is hard to select menu list items on mobile device

**Describe the improvement you'd like**
Make list items larger

**Additional context**
Current:
<img width="377" alt="Screen Shot 2021-07-20 at 11 38 17 AM" src="https://user-images.githubusercontent.com/3605988/126353621-77bd2c53-3407-4b39-8b30-3c9692daba3f.png">

**Comment by jasontk19** [comment]
The info, projection, and measurement menus should all be consistent as well.  A good target height is probably around 44px since that's usually what's considered the minimum for a mobile touch target.


<img width="452" alt="Screen Shot 2020-10-01 at 8 51 01 AM" src="https://user-images.githubusercontent.com/1480000/94811420-584ed700-03c3-11eb-8964-c050285ce4cc.png">
<img width="459" alt="Screen Shot 2020-10-01 at 8 51 07 AM" src="https://user-images.githubusercontent.com/1480000/94811423-58e76d80-03c3-11eb-9d36-2f50b37f6adb.png">
<img width="451" alt="Screen Shot 2020-10-01 at 8 51 17 AM" src="https://user-images.githubusercontent.com/1480000/94811426-59800400-03c3-11eb-96d9-f6bf2cdd9737.png">
