### ISSUE TITLE
Toolbar buttons retain grey background if clicked and that dialog is closed

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2720]
**Describe the bug**
Toolbar buttons retain grey background if clicked and that dialog is closed.

**To Reproduce**
1. Click camera image download icon
2. Close by clicking 'x' -or- clicking else where in the screen
3. See camera toolbar button retains grey background

**Screenshots**
This is after clicking the camera, and closing the image download dialog by clicking 'x'.
![image](https://user-images.githubusercontent.com/24417194/75587135-d28d3680-5a43-11ea-8cf4-00426548ebb8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jasontk19** [comment]
This appears to be happening due to a change between `v4.3.1` -> `v4.4.1` of Bootstrap.

```
/* v4.3.1 */
.btn-secondary:focus, .btn-secondary.focus {
  box-shadow: 0 0 0 0.2rem rgba(130, 138, 145, 0.5);
}
```

```
/* v4.4.1 */
.btn-secondary:focus, .btn-secondary.focus {
  color: #fff;
  background-color: #5a6268;
  border-color: #545b62;
  box-shadow: 0 0 0 0.2rem rgba(130, 138, 145, 0.5);
}
```

We could just override the styles for `:focus` states but, maybe a better step toward future accessibility enhancements would be to bring in [something like this](https://github.com/ten1seven/what-input) to differentiate between mouse initiated focus and keyboard initiated focus, so that we can change the styles for mouse focus only.
