### ISSUE TITLE
Tours are not zooming to the correct location

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2929]
**Describe the bug**
On SIT, when starting a tour e.g. Australia fires, the first step should zoom to Australia, but the map is not zooming to the location. 

**To Reproduce**
1. Go to SIT
2. Click on Australia fires tour
3. See that map does not zoom to Australia
4. same issue with other tours

**Expected behavior**
The map should zoom to the correct location 

**Screenshots**
<img width="1438" alt="Screen Shot 2020-06-02 at 4 41 26 PM" src="https://user-images.githubusercontent.com/10747923/83639844-4aa25580-a579-11ea-9d5f-8fa34491a4e5.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome, firefox

**Comment by edplato** [comment]
Started debugging this. The issue appears to arise at https://github.com/nasa-gibs/worldview/commit/f84c1a203917632af0741d9b14c80fcc9abf05c1

If I replace the `package-lock.json` with the previous commit's `package-lock.json` and run `npm install && npm run build`, it seems to work normal. I'm not sure if this commit is the cause or just a catalyst of the real issue. This led me to removing the `package-lock.json` from `develop` and running `npm install && npm run build`, which fixes the bug. I tested `npm run build:prod` and that seems to be fixed as well. I'm not sure if this a valid direction for a fix or not since we lose the `package-lock.json`.

Any thoughts?

**Comment by Benjaki2** [comment]
I don't see a problem with reverting to an older package-lock since it seems like a dependency update made this happen.

**Comment by jasontk19** [comment]
I guess my only concern with that approach to fix this is... what happens when that dependency eventually _does_ get updated in the future?  I guess we could kick this can down the road by reverting the package-lock but maybe still need to leave the issue open?
