### ISSUE TITLE
Investigate npm install node-gyp contextify issue

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#303]

**Comment by ZachTRice** [comment]
Finally figured out a solution for this. Seems like the biggest issue is getting the Visual C++ compilers installed on Windows. Even after installing different version of visual studios, I was still getting warnings that VCBuild.exe could not be loaded (error MSB3428). Seems this is a very [common problem](https://github.com/nodejs/node-gyp/issues/307) amongst Windows users.

The best solution is to install this npm package:  https://www.npmjs.com/package/windows-build-tools
 
    # run in administrator privileged command prompt window 
    npm install --global --production windows-build-tools 

This package installs the Visual C++ Compilers, Build Tools, and SDKs needed to build many NPM modules without conflicting with current Visual Studio installs. It also installs the latest version of Python 2. To use Python in cmd.exe and powershell, you need to add the following path to Windows Environmental Variables path.

    %USERPROFILE%\.windows-build-tools\python27

**Comment by ZachTRice** [comment]
Without this work around I was unable to run `grunt`. Usually the contexitfy/node-gyp step fails and is skipped but several times when the build fails the process is aborted. See here:
![npm_errors](https://user-images.githubusercontent.com/17348884/27914018-e881fbe2-622f-11e7-9931-e2e126b7efe5.png)

**Comment by ZachTRice** [comment]
I will update the documentation, submit a PR and then we can close this issue.

**Comment by ZachTRice** [comment]
Synopsis:
The problem occurring was that node-gyp adds a global folder to c:\Users\[username]\.node-gyp which occasionally needs rebuilt to match the node version you are running. Notice in my screenshot above the node-gyp subfolder was reading v3.4.0; after a successful rebuild, my .node-gyp folder now reads v6.11.0 matching my node version. Without the proper compilers, this folder was not being rebuilt and skipped which occasionally was ok, but in this instance it was not. 

In the future, we might want to figure out which package requires contextify and see if there is an updated version which doesn't rely on this package. Especially since ["You don't need this module on node >= 0.12"](https://github.com/brianmcd/contextify#you-dont-need-this-module-on-node--012)

Either way, these compiler issues effect other npm packages so Windows users should definitely have windows build tools installed first.
