### ISSUE TITLE
Links do not shorten in test environment

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#310]
Experiencing 503 error (API key not found) when deploying to testing environment.

**Comment by rboller** [comment]
It appears that [shorten.cgi](https://github.com/nasa-gibs/worldview/blob/master/web/service/link/shorten.cgi#L163) retrieves bitly.json from an etc directory on the host system in order to keep the api key secret.

And installation of that bitly.json file seems to only happen in the official deployment processes.

**Comment by Benjaki2** [comment]
We could generate a config file that uses a different bit.ly key when we are in the development environment. Would be a bit of a work and isn't something that will work locally for others who clone the app unless they create their own config/bitly account. Something to discuss further.

**Comment by ZachTRice** [comment]
@Benjaki2, Now that we have the development branch set up. Can this be marked as complete?

**Comment by Benjaki2** [comment]
Ideally we would have a way to config this locally. I think this issue should continue in the backlog.

**Comment by localjo** [comment]
Link shortening now works in test environments
