### ISSUE TITLE
Investigate grouping of related layers (e.g. all OSM layers in one "group")

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#3185]
**Is your feature request related to a problem? Please describe.**
When managing sets of related layers (e.g., Coastlines, Labels, Roads), a user may want to enable only a subset of those layers at any given time but toggle them on/off, as needed.  Our current solution treats each layer separately which takes up a good bit of real estate.  So ideally we'll want to make sure the user is aware of all of the options and can adjust them as needed BUT not take up an unnecessary amount of real estate.

As an upcoming use case, we plan to split all of our OSM layers out into individual layers and some kind of grouping should help:
* Coastlines
* Borders
* Labels
* Roads

An example of our existing layout:
![sidebar.png](https://images.zenhubusercontent.com/5d55bcb191a5dd02bc6d22d9/7d7fbc7b-db9d-4f2d-9948-6bff2249df47)

**Describe the solution you'd like**
It would be helpful to group these similar layers together and manage them in one place.  One idea is a sort of "accordion" expansion of related layers. 

Another would look similar to our existing "classification" palettes to toggle on/off individual layers within a "parent" layer.
![layer-toggles.png](https://images.zenhubusercontent.com/5d55bcb191a5dd02bc6d22d9/9b655ca0-6857-4fd7-a85e-07869472d4f7)

Another would work like our "add related orbit track" feature:
![add-related-layer.png](https://images.zenhubusercontent.com/5d55bcb191a5dd02bc6d22d9/31726853-414a-4467-9fb4-5c0cc354b0df)

There of course may be other options, too!  So this ticket is to investigate design options for how we could build this functionality and if it applies more generally to other layers (e.g. our multitudes of fire and SST layers).

**Comment by jasontk19** [comment]
Per Slack discussion:

The approach will be to attempt to make use of the `layerGroup` property in the layer configs in order to define groups.  Since we want to allow the user to be able to have total flexibility of individual layer ordering, it was proposed that we use a global toggle option in order to enable/disable layer grouping.  Users should be able to re-order groups, re-order layers within a group, and if desired ungroup all layers and re-order individual layers.  

A URL param for whether or not layers are being grouped should be added so that the state of layer/group orders can be retained in the permalink.  If the app is in a state with numerous layers loaded in an order that doesn't comply with their grouping and grouping is turned on, the user should be warned that the layer order will have to be changed in order to group them.  Additionally, it would nice if the user could undo this action once taken if they decide they don't like the ordering after groups have been applied.
