### ISSUE TITLE
Change polar product picker to list of measurements

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#327]
Make it look the same as when you click the "All" category in the product picker.

**Comment by rboller** [comment]
After some discussion this morning, we decided that there should be three configurable viewing options for the product picker on a per-projection basis: "categories", "measurements", and "layers".  

"Categories" is what's currently shown in the geographic projection.

"Measurements" would look like what happens when you currently click on the "All" category in the geographic view.

"Layers" is what we currently have in the polar views which is a raw listing of available layers for the current projection.
