### ISSUE TITLE
layer.mob.init.12 - Upper portion of text slightly obscured in facets in mobile view

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3325]
**Describe the bug**
Upper portion of text slightly obscured in facets in mobile view.

**Expected behavior**
Upper portion of text shouldn't be obscured.

**Screenshots**
![Screen Shot 2021-02-05 at 3.04.43 PM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/9dbe216b-0102-4d8f-ace2-b2616dc76e83)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version: 78.6.1esr (64-bit)

**Comment by jasontk19** [comment]
Hmmmm... I think it's because your browser is zoomed in.  At the default zoom level in both Chrome and Firefox it looks fine:
![Screen Shot 2021-02-08 at 11 22 32 AM](https://user-images.githubusercontent.com/1480000/107248194-0d437100-6a00-11eb-84c3-56ff1f9be146.png)

Zoomed in one step looks fine in Chrome but gets slightly cut off in Firefox:
![Screen Shot 2021-02-08 at 11 23 37 AM](https://user-images.githubusercontent.com/1480000/107248360-382dc500-6a00-11eb-9560-85c2cc515ee6.png)

Since this is the mobile layout where you're unlikely to be zoomed in or out like this on an actual device, I wonder if it's worth fixing?

**Comment by minniewong** [comment]
hmmm - I double checked and made sure it was "actual size", but it's still slightly cut off at the top in my version of Firefox (78.6.1esr (64-bit))

**Comment by jasontk19** [comment]
Weird, I am on version 78.4.0esr and only see it when I zoom in or out one step 🤷🏻 

I'll take a quick look and see if it's an easy CSS tweak to fix.
