### ISSUE TITLE
Bring back the Iceberg natural event icon

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3428]
**Describe the bug**
Somewhere along the way, we lost implementing our Iceberg natural event icon for Icebergs and now use our Sea and Lake Ice icon. I like both, but the Iceberg one looks more intuitive to me. I think some logic needs to be added where the event marker types are parsed due to EONET Iceberg events categorized as:

```
categories: [
  {
    id: "seaLakeIce",
    title: "Sea and Lake Ice"
  }
],
```

I'm sure there is legitimate Sea and Lake Ice that deserve the Sea and Lake Ice icon, so just an idea for parsing is if "Iceberg" isn't in the event title then use the Sea and Lake Ice icon.

<img src="https://user-images.githubusercontent.com/24417194/112511661-00d56680-8d69-11eb-854e-2805216908f7.png" width="250">
<img src="https://user-images.githubusercontent.com/24417194/112511689-07fc7480-8d69-11eb-9ada-1277d547e88c.png" width="250">

**Comment by jasontk19** [comment]
Since we represent categories by their icon in the sidebar, I don't think we want to use two different icons for one category based on whether it's an iceberg or sea/lake ice.  That said, the current sea and lake ice icon looks a lot like the water color icon anyway and, most of these events are icebergs, and the iceberg icon looks cool.  So, I think we're fine doing a one to one swap.

![Screen Shot 2021-06-08 at 2 21 43 PM](https://user-images.githubusercontent.com/1480000/121237273-df165680-c864-11eb-95c0-9b2c778751d0.png)
