### ISSUE TITLE
Allow future multidates in date range for active layer building without new requests

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3464]
**What existing feature could be improved?**
Allow future multidates in date range for active layer building without new requests. 

**Additional context**
Additional discussion in PR #3452

**Comment by jasontk19** [comment]
Would it be possible to update the ticket description with more info on what the problem is exactly that we're trying to fix?  Is it just that we make tile requests on a daily basis when the last date in `dateRanges` at build time is before the day you are using the app?  It's been so long since the discussion about this I'm kind of fuzzy.

**Comment by edplato** [comment]
Exactly, the issue is that new requests are being made for each day in multiday ranges (e.g., MODIS_Combined_L4_LAI_4Day) when the date requested was beyond the known GC date range from when the app was built. The intended fix is to continue flooring these requests and only make one request for the multiday range.
