### ISSUE TITLE
Imagery loaded at the bottom doesn't seem to update when there is a fire layer loaded at the top of the list

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3523]
**Describe the bug**
Imagery loaded at the bottom of the layer list doesn't appear to update when you step forward a few days, and then step backward a few days, when you have one fire layer loaded at the top of the layer list. (if there are more than one fire layers loaded, the imagery updates)

**To Reproduce**
1. Go to https://go.nasa.gov/2SpmZcx
2. Click on forward arrow in the timeline for a few days
3. Click on the back arrow the same number of days (or less)
4. See error - imagery does not update, though fire vector does.

**Expected behavior**
The imagery should update every time you change the date. 

**Desktop (please complete the following information):**
 - OS:OSX
 - Browser: Chrome and Firefox

**Comment by edplato** [comment]
If the reference layers are removed from the url, then it seems to change layer dates as intended: https://worldview.earthdata.nasa.gov/?v=-87.20548449191865,-30.29273472590551,-24.746266849662888,0.3675843510872312&l=MODIS_Combined_Thermal_Anomalies_All,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor&lg=true&t=2021-05-17-T14%3A14%3A56Z.

The issue appears to start somewhere around 68d457cdd0582a6a5c0eb381eecbb7109bbd04a2

I'm not seeing this issue in a54a3e9e4c4eb3fc5124ae52fb7813f4ddb02e58 before `15m` reference layers are added - note, however, no reference layers are included since the `15m` reference layers are omitted from the url, so then replacing the `15m` layers that url works as normal http://localhost:3000/?v=65.14772306523187,10.36728915299313,128.14008429936578,41.28932064422813&l=VIIRS_NOAA20_Thermal_Anomalies_375m_Day,Reference_Labels%20(hidden),Reference_Features(hidden),Coastlines,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2021-05-09-T14%3A02%3A24Z

**Comment by edplato** [comment]
The date update issue is visible in `ui.js`, possibly from `setStyleFunction` related to vector layers, which breaks this `activeLayers` iteration: https://github.com/nasa-gibs/worldview/blob/main/web/js/map/ui.js#L779 which then causes the base layer date update to be skipped here: https://github.com/nasa-gibs/worldview/blob/main/web/js/map/ui.js#L803.

**Comment by Benjaki2** [comment]
I don't know exactly why this function would break it, aside from it being a large process. I tried making it async and that seems to work. So maybe that is a decent solution?
```
        setTimeout(() => {
          setStyleFunction(def, vectorStyleId, vectorStyles, null, state);
        }, 10);
```

**Comment by edplato** [comment]
I couldn't see any blocking issues with the `setStyleFunction` either. Your suggestion fixes it for me and passes related tests, so I think we should go for it.

**Comment by minniewong** [comment]
Seems to be back again in UAT
