### ISSUE TITLE
ERR_CONNECTION_REFUSED on windows

### ISSUE THREAD

**Issue by spatiallysaying** [nasa-gibs/worldview#3535]
**Describe the bug**

I get ERR_CONNECTION_REFUSED on windows when I open http://localhost:3000/ in Chrome or any other browser.

**To Reproduce**
1. Install Docker Desktop version 3.3.3 on Windows 10
2. Install all dependencies 

apt update
apt upgrade
apt install curl
apt install nodejs

--Using Ubuntu
curl -fsSL https://deb.nodesource.com/setup_14.16| sudo -E bash -
sudo apt-get install -y nodejs

--Using Debian, as root
curl -fsSL https://deb.nodesource.com/setup_14.16 | bash -
apt-get install -y nodejs

apt install python-is-python3
apt install python3-pip
apt install pipenv
apt install git

export NODE_TLS_REJECT_UNAUTHORIZED=0

3. Use the steps to install worldview
git clone https://github.com/nasa-gibs/worldview.git
cd worldview
npm ci

npm run build
npm start
4. See an error
This site can’t be reached; the localhost refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser:Chrome
 - Version: Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**

**Comment by jasontk19** [comment]
Hi @spatiallysaying.  I'm afraid there's not much we can do on our end to fix this since it's specific to how you are trying to set up your environment (inside a docker container).  When we run the app locally for development, we don't run it inside a docker container.  You should be able to do this in Windows or MacOS without much trouble.

Is there a specific reason you need to run it in a Linux container?  And if so, is your container set up properly to expose the port you are trying to connect to?
