### ISSUE TITLE
Global settings panel

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3667]
**Is your feature request related to a problem? Please describe.**
Global settings panel with options to change global settings.

Ideas for possible toggleable options:

- temperature unit
- distance unit
- dateline on/off
- tooltips on/off
- coordinate format

Example using settings button located in toolbar.
![image](https://user-images.githubusercontent.com/24417194/128539450-f7b142e7-dd56-43ae-b1a5-0961a1a048cc.png)

**Comment by jasontk19** [comment]
Added coordinate format.

We should definitely differentiate between layer-specific configurable options (temp units) vs app feature specific options (distance unit).  We also may want to be careful without how much we offer configurability for since we don't have a way to tie it to a user account or anything.

**Comment by minniewong** [comment]
Moved to WV-1949
