### ISSUE TITLE
[DEVELOP] Error changing date when coordinate location marker is present

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3694]
**Describe the bug**
Error changing date when coordinate location marker is present on map.

**To Reproduce**
1. Go to 'http://localhost:3000/?v=-117.32122685424919,24.4475775467871,-96.13218226993986,38.474390204003285&l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m(hidden),VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=false&s=-100.9626,33.3787&t=2021-06-10-T02%3A20%3A19Z'
2. Click on left date arrow
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/131175059-ec5884ab-54c6-42c1-9a45-7abb9a1db771.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jasontk19** [comment]
@edplato It looks like the location markers are being added to the map layers array and, since the location marker doesn't have a `wv` property, it breaks here.  Other map items like event markers/tracks and measurements are not included in this layers array which otherwise only includes Worldview imagery layers.  I think the right fix might be to change the way the location marker gets added to the map so it doesn't get picked up along with imagery layers elsewhere in the app which seems like it has the potential to cause other bugs.  Any thoughts?
![Screen Shot 2021-08-30 at 12 10 52 PM](https://user-images.githubusercontent.com/1480000/131385110-60fb5aa6-76cd-4628-8b28-1e2479113550.png)

**Comment by jasontk19** [comment]
To clarify, other map items are created as "overlays" rather than "layers" and so don't get included in the map layers array.  I'm just curious if there is a reason the location marker needs to be a vector layer?

**Comment by edplato** [comment]
That makes sense. I based it off the OL examples page creating a VectorLayer to add a marker. I'm not sure what limitations if any there are by refactoring it to an overlay vs a layer.

**Comment by jasontk19** [comment]
I'm working through that now... it looks like we are making vector layers to render measurements but they aren't being added to the map in the same way so they aren't showing up in the layers array.  I'll try to figure it out.
