### ISSUE TITLE
Add CSS Autoprefixer as a dev tool

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#372]
* Probably will be removed after preprocessors are incorporated.

**Comment by ZachTRice** [comment]
I think we should run autoprefixer on the tracked css files rather than piping those prefixes into only the debug/release folders because these css changes should be tracked. If someone is committing new css changes, they add a property that has fallback prefixes, those prefixes should be added and tracked. This also means we should run autoprefix once, check the changes, and then commit all the css files again.

**Comment by minniewong** [comment]
Look into Travis/CI
