### ISSUE TITLE
Preserve Active Layers When Changing Event Date

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#388]
e.g. Sea Ice/Icebergs events - Brightness Temperature is loaded but not on when you select an iceberg event. Enter some logic so that when you turn on the brightness temperature layer, it will stay on if you change the event date

**Comment by minniewong** [comment]
If you've turned on a recommended layer, and change the event date, the recommended layer should stay on

**Comment by localjo** [comment]
I'm thinking about making this a simple text filter;

![screen shot 2017-08-03 at 4 11 52 pm](https://user-images.githubusercontent.com/516388/28941722-e96a8432-7866-11e7-90d7-136701cba7f7.png)
![screen shot 2017-08-03 at 4 14 31 pm](https://user-images.githubusercontent.com/516388/28941721-e9695c1a-7866-11e7-9153-17af4f3f530d.png)

That way you could filter by event types, just by starting to type something like "Tropical Storm", "Iceberg", "Fire", etc. And you could also filter for specific names of events like "A68B" or "Sandy" or "California", etc.

I could also add a subtle "x" button in the filter input to clear it quickly.

Thoughts?

**Comment by localjo** [comment]
Going to tackle #407 first because it'll be easier to test this if I can quickly filter to relevant events.

**Comment by localjo** [comment]
Is there another way to "change event dates" other than clicking on an event in the list with the same name on a different date? Ie;

Step 1 (click on initial event);
![screen shot 2017-08-03 at 4 24 46 pm](https://user-images.githubusercontent.com/516388/28942188-741d1b20-7868-11e7-907d-eff86ef011bd.png)

Step 2 (click on different instance of event);
![screen shot 2017-08-03 at 4 25 05 pm](https://user-images.githubusercontent.com/516388/28942189-741d34ac-7868-11e7-9c44-a6f5a6df3995.png)

I guess you could also manually scrub the timeline looking for other event dates, but that would leave the state of the layers the same, so I'm guessing that this issue is referring only to the user action I described above. Just checking that there aren't any other UI actions (yet) that would "change event dates". :)

**Comment by rboller** [comment]
@localjo those events that you listed happen to be different events (A68B vs A68A) and happen to only have one date associated with them.  Others like Iceberg B15Z have a ton of them:

![screen shot 2017-08-03 at 5 35 37 pm](https://user-images.githubusercontent.com/7243823/28944878-423376b8-7872-11e7-96c9-d43e6b507421.png)

**Comment by localjo** [comment]
@minniewong What if we change events entirely, but it's the same event type; ie, we select a wildfire, change some layers, and then select another wildfire. I think we should only update the layers when we select a different event type. What do you think?
