### ISSUE TITLE
Fonts: Implement better cross-browser support

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#393]
There are a few bad practices in regards to fonts within the CSS files.
1. System specific fonts are used as the main font.
Example: 'Lucida Sans', 'Monaco', Arial;

Lucida Sans is a Microsoft specific monospaced font, Monaco an Apple specific monospaced  font, and Arial a sans-serif font.
Check: http://www.cssfontstack.com/

It would be better in this situation to use 1 cross-browser monospace font that we have downloaded and included via @font-face or via a google CDN. Also the more appropriate fallback stack for monospace is:
"Lucida Console", Monaco, monospace;

2. Fonts imported via @font-face should have better fallback support other than truetype
Example: 
```
@font-face {
    font-family: open_sans_light;
    src: local(open_sans_light), url('../font/OpenSans-Light.ttf') format('truetype');
    font-weight:300;
}
```
Right now we are only loading in truetype fonts where as we could be providing better cross-browser support by using eot, woff, file formats.
See: https://css-tricks.com/snippets/css/using-font-face/#article-header-id-0

**Comment by ZachTRice** [comment]
#338, "Font Awesome Icons not loading in IE11", is another cross-browser font-related issue that.

**Comment by ZachTRice** [comment]
Areas of the site that use `'Lucida Console', 'Monaco,' monospace` should probably be replaced by Roboto Mono. It supports all font weights. We can host locally and import via @font-face as we do now with Open Sans

https://fonts.google.com/specimen/Roboto+Mono

**Comment by rboller** [comment]
Took a look through this... overall looks good though I'd suggest some updates.  My notes:

- the layer label placement is much better (ie good padding)
- the new font height matches the old one exactly, but the new one is horizontally squished which makes it a bit harder to read - would help if we could space it out a bit more
- in the product picker modal, there isn't as much of a distinction between the category and measurement labels - we should maintain and possibly intensify that distinction 
- the height of data download layer list item is much taller than original, is that intentional?

**Comment by ZachTRice** [comment]
These are all great suggestions. I'll work on making these changes. 

As for your last question, no that wasn't my intention. I added margin bottom to the titles and paragraphs in this area which increased the overall heights. I can fix this by decreasing the wrapping div's padding. Good catch.
