### ISSUE TITLE
Orbit track descriptions are incorrect in the search results and layer list

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#477]
![screen shot 2017-08-21 at 4 02 49 pm](https://user-images.githubusercontent.com/10747923/29536366-87662542-868b-11e7-9669-0e63bcbe93a5.png)

When looking at the orbit track descriptions using search and in the layer list, the orbit tracks have the incorrect layer description (except for Suomi NPP). When using the product picker, the descriptions are correct for all of the orbit tracks.

**Comment by ZachTRice** [comment]
The orbit tracks are actually attached to multiple sources so when it it looping through, it is only grabbing one of the source descriptions. I'll work with it more to see if I can attach each of the sources it is attached to but even then it will be hard to tell which source you selected orbit tracks within since all descriptions would be lumped together. 

Another separate issue I noticed is that if I check and add the Aerosol Optic Depth - Terra/Modis - Desc/Day orbit track, it is not checked in Cloud Top Temperature - Terra/Modis - Desc/Day; even though these are the same orbit tracks. Manually selecting both and then unselecting one does unselect both though so the expected results are inconsistent.
