### ISSUE TITLE
Convert all raster icons to svg

### ISSUE THREAD

**Issue by CodeMacabre** [nasa-gibs/worldview#566]
As requested by @Benjaki2; I can start working on this later this week.

Could this have any performance issues in IE (related to [this](https://github.com/nasa-gibs/worldview/pull/463#issuecomment-329298257)) or have you found a workaround / solution? @localjo / @ZachTRice?

**Comment by ZachTRice** [comment]
There is definitely an issue with using too many SVGs at the same time with IE. So, we had to switch back from using SVG to images on the map pins. We might be able to switch the ones out the icons in the sidebar but we should definitely be mindful of how this is affecting IE performance.

**Comment by CodeMacabre** [comment]
I'll try it out and test IE performance as I go. Hopefully the relatively small amount of icons in the sidebar won't make much of an impact. Alternatively, we could look for Font Awesome equivalents for some of the raster icons.

**Comment by localjo** [comment]
Hi @CodeMacabre :) Excited to have your contributions!

The issue you mentioned was related to generating hundreds of SVG elements on the map at the same time. Getting SVGs to work well in IE can be tricky, and takes some trial and error. If you look at the icons in the tab headers, that might be a good approach to copy. Or the ones in the Events tab, in the list of events. The approach that seems to work well for us is using SVGs as CSS backgrounds.

In the future, we may want to change those to be inline SVGs [the same way that GitHub does](https://github.com/blog/2112-delivering-octicons-with-svg), but we need to make some improvements to our build scripts before we can do that in an efficient way.

In order to support that future change, and keep our SVG files organized, icons should either all be in individual SVG files like the [event icons](https://github.com/nasa-gibs/worldview/blob/master/web/images/natural-events/icon-default.svg?short_path=582f8b6) or included in [the existing SVG icon sprite](https://github.com/nasa-gibs/worldview/blob/master/web/images/icon-sprite.svg).

I found that the easiest way to edit/save a clean SVG file that sticks to the SVG spec and doesn't add extra metadata is to use [Boxy SVG](https://boxy-svg.com/). If you prefer to use Illustrator or Inkscape or something, that's fine, but make sure that it doesn't generate changes to the code for the existing glyphs in the current files (especially the sprite file), and strip out any unnecessary attributes and comments from new files you generate to keep them clean.

One other thing to keep in mind when generating SVGs is to use the same height/width/viewbox size when editing the icon that you intend for the icon to be displayed at. That keeps the file size down and helps mitigate potential scaling issues. So, for example, if you're displaying at icon at 30x30, don't create and SVG with a height/width/viewbox of 3000x3000. You can either adjust the height/width/viewbox before you create the icon, or create the icon at a larger size and then scale it down before saving it.

Let us know if you have any questions. :) Thanks again for the contributions!

**Comment by CodeMacabre** [comment]
Thanks for the advice @localjo, that's a big help! I should be able to work on the icons this week.

**Comment by Benjaki2** [comment]
@minniewong I think Features #1084 & #1508 mostly resolve this issue.

**Comment by minniewong** [comment]
@Benjaki2 - Great thanks! We'll close this ticket.
