### ISSUE TITLE
Implement better mobile detection

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#709]
Right now, we do not have a consistent way of recognizing mobile devices such as tablets and mobile. The tour code, for example, uses a function called `validScreenSize` which looks for a window width and height. What we really want here is an ability to detect mobile devices. We use separate functions throughout the rest of the code base for similar mobile / screen size detection. Some possible solutions are:

- Detect mobile devices using userAgent strings: this is an iffy solution because there are so many userAgent strings and they are constantly changing but probably the best.
- Use modernizer to detect touch events but with hybrid desktop / touch-enabled laptop devices, this is not consistent either.
- Use a combination of the above solutions plus screen-size detection.

**Comment by minniewong** [comment]
From WV-1510: For certain devices (e.g., iPhone 6+), Worldview assumes it's a desktop display due to the large resolution. However, it's a device with a high pixel density.

This ticket is to attempt other mechanisms to handle this situation.Style

If it's possible to get a reliable value, it could be helpful to use the device's DPI measurement.

**Comment by minniewong** [comment]
From WV-1691: Disable data download on touch screen devices: Currently uses pixel with to disable. We should use touch screen detection.

**Comment by ZachTRice** [comment]
This was largely handled in a past 2.x update
