### ISSUE TITLE
Pressing tab after a date input entry no longer enters date [date.input.8]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#787]
Entering the number 6 in the month input and pressing tab when the current value is `JUN` should revert the month to august but instead the 6 remains and you now focus on the day input without reverting the value.
<img width="346" alt="screen shot 2018-03-20 at 1 57 21 pm" src="https://user-images.githubusercontent.com/3605988/37673461-a45d750e-2c46-11e8-893f-cbf496c9b68b.png">

_tested in Chrome_

**Comment by ZachTRice** [comment]
@Benjaki2 I am not able to reproduce this. Entering 8 in chrome changes the month for me as it does in production. Can you re-verify this is a new issue?

Also, production does not handle invalid values either. If you open the console in production and enter a character instead of a number and tab, you will receive a lot console errors. The testing branch actually handles this better by not throwing errors and just ignoring it. (Though, it would be best if the value / month abbr reset when tabbed).

**Comment by Benjaki2** [comment]
@ZachTRice I update the description of the problem and removed it from the Temporal Resolution project ⬆️  as this is not a new error.
