### ISSUE TITLE
Explore OSM Vector Tiles/Raster Tiles

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#886]
Explore current options for updating the OpenStreetMap layers e.g. coastlines, roads, place labels etc. and come up with a plan of action.
Also to address: https://wiki.earthdata.nasa.gov/display/WOR/Worldview+Map

**Comment by rboller** [comment]
Per a recent discussion with FIRMS, we'll also want to consider serving these updated layers as vector tiles.  

And regardless, they'll be interested in evaluating the raster/vector tiles that we produce.

**Comment by rboller** [comment]
We should also look at updating our Antarctic coastlines from SCAR during this process.

**Comment by rboller** [comment]
@jasontk19 here is some additional background on this task.

**Goals**

- Update our existing layers for coastlines / borders / roads / labels to reflect the latest available data from OpenStreetMap (OSM) and other sources and make user-suggested updates
- Provide additional zoom levels to at least match our upcoming higher-resolution imagery (30m/pixel)
- Be able to relatively easily regenerate the layers periodically to stay up-to-date

**Previous approach**
- We downloaded and processed [Planet OSM](https://planet.openstreetmap.org/), [Natural Earth](http://www.naturalearthdata.com/), and [SCAR](https://scar.org/data-products/antarctic-digital-database/) into a database running on a local server
- We used [TileMill](https://github.com/tilemill-project/tilemill) (which then became Mapbox Studio (which then became [Mapbox Studio Classic](https://github.com/mapbox/mapbox-studio-classic))) to connect to that database and interactively craft stylesheets that worked well with satellite imagery from the OSM/Natural Earth/SCAR data
- After we were happy with the styles, we applied them to the data using [Mapnik](https://mapnik.org/) to generate raster tiles which match the GIBS tiling grid and zoom levels

**Possible approaches for the present**
- Resurrect our old code with updated data
- Use others’ existing vector tiles (e.g., [Esri](https://www.esri.com/arcgis-blog/products/developers/mapping/design-custom-basemaps-with-the-new-arcgis-vector-tile-style-editor/) or [Mapbox](https://www.mapbox.com/mapbox-studio/)) and apply a custom style that works well with our satellite imagery; challenges include being able to use them in our map projections (geographic, Arctic polar stereographic, Antarctic polar stereographic), potential costs associated with using others’ services, compatibility of the snapshot tool with their vector tiles
- Create a new workflow based on modern tools/libraries, e.g., [OpenMapTiles](https://openmaptiles.org/) which provides a set of open source tools to generate and serve vector and raster tiles; challenges still include ability to use them in our map projections, though folks from OpenMapTiles have [claimed](https://www.maptiler.com/blog/2016/08/tileserver-gl-maps-with-gl-json-styles.html) that it’s possible

**Outstanding questions**
- Can we simply serve vector tiles and style them on the client rather than pre-generating raster tiles?
  - And if we did this, can we just use web mercator-based vector tiles and reproject on the client side (at least for the geographic projection)?
  - Can we still take properly-styled snapshots if we don’t have pre-generated raster tiles?

@mike-mcgann please update/add anything I missed.

**Comment by minniewong** [comment]
Needs to be updated for HLS
