### ISSUE TITLE
Add a "reset" button

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#92]
Per user requests, add an ability to reset Worldview to its default state without having to manually revert the URL to https://worldview.earthdata.nasa.gov/

**Comment by localjo** [comment]
Is there a UI for this, or any previous discussion about how it should look?

**Comment by localjo** [comment]
I'm thinking I could approach the UI in a few different ways;

1) We could make the logo a link back to the root. This would be a pretty conventional UI pattern, but since it would cause users to lose their state, we'd probably want to add a confirmation dialog. The button's function also might not be clear to a user who's thinking about how to reset their state, but not about how to "go home".

2) We could add separate buttons to reset layers to the default and to reset the timeline to today. It seems to me that those would be useful buttons to have either way. We can add a "Reset Layers" button below the "Add Layers" button. This could have a confirmation dialog. We can also add a "Today" button between the arrows on the timeline. No need for a confirmation dialog for that one, in my opinion.

3) We could add a "Reset UI" button in the info menu in the top right that's just a link back to the root. Possibly a confirmation dialog as well, since there's no obvious way to recover the lost state if someone clicks on it accidentally.

I'm in favor of implementing both 2 & 3. Any thoughts on this?

**Comment by localjo** [comment]
Fixed by #449. I thought GitHub would close this issue automatically. Maybe that setting isn't enabled.

**Comment by localjo** [comment]
Oh! I know why it didn't close automatically. It was merged into `development`, not `master`. @Benjaki2 Should we leave issues open until they land in `master`?

**Comment by Benjaki2** [comment]
@localjo We usually wait until it goes into `master` to close but when we are done with something, we throw the `ready for test` label on it

**Comment by localjo** [comment]
Ok, added the label, and reopened. I'm curious to see if merging `development` into `master` will automatically close the issue, based on the keywords I used in the PR description. https://help.github.com/articles/closing-issues-using-keywords/

**Comment by minniewong** [comment]
Change "it's" to "its"

**Comment by localjo** [comment]
Fixed this in `development` branch directly. No additional PR.
